### ISSUE TITLE
invalid yaml version specified in config.go

### ISSUE THREAD

**Issue by jacec** [walter-cd/walter#124]
Hi, FYI there seems to be an invalid import in ```config.go```

I replace the import for ```github.com/go-yaml/yaml``` with ```gopkg.in/yaml.v2```

and, for what it's worth, there's an underscore in a variable name and missing comments on exported funcs in the same file, which gofmt comlains about. I can branch and fix myself if that helps, but as it's such a minor complaint I thought I'd create an issue first :)

:+1: for the work so far

**Comment by takahi-i** [comment]
Hi @jacec. Thank you very much for the comments on the Walter source! That would be very helpful if you give us the pull request for the fixes.

**Comment by jacec** [comment]
Hi @takahi-i my bad, I didn't see you were running ```godep``` in your build script, and you explicitly referencing a particular rev of go-yaml.
```
"ImportPath": "github.com/go-yaml/yaml",
"Rev": "1b9791953ba4027efaeb728c7355e542a203be5e"
```
Given this, my suggestion of ```gopkg.in/yaml.v2``` is invalid, although at some point you might want to take a newer revision.
