### ISSUE TITLE
Support for HCL and JSON configuration [Enhancement]

### ISSUE THREAD

**Issue by jacec** [walter-cd/walter#127]
In addition to YAML, it would be good to have the ability to support additional configuration languages.

[HCL](https://github.com/hashicorp/hcl) (Hashicorp Configuration Language) provides it's own, plus the ability to support JSON. See the repo for a good description on why this is a good addition to YAML.

I have a fork almost ready for a pull request.

**Comment by jacec** [comment]
This is a duplication of @ainoya's #18, but the pull request still stands and should considered for #18 also.

**Comment by Hades32** [comment]
Any JSON is already valid YAML, so that is already done :)

**Comment by mizzy** [comment]
We will not support other than YAML currently. So I close this.
