### ISSUE TITLE
Request for a new release includes suppress_all feature

### ISSUE THREAD

**Issue by takyoshi** [walter-cd/walter#161]
Hi.

We install `walter` using `chef` from github release source, so would you be willing to release a new version  includes suppress_all feature if you can?

thank you.

**Comment by takahi-i** [comment]
Thanks for the comment @takyoshi! I will release the new version of Walter this week.

**Comment by takahi-i** [comment]
Hi @takyoshi! I made the release (v1.4.0) containing the new features such as **suppresll_all**. 

The following is the URL of the release.

https://github.com/walter-cd/walter/releases/tag/v1.4.0 

Let me know when you have any problem in the binaries.

**Comment by takyoshi** [comment]
I'm very graceful!

**Comment by takahi-i** [comment]
👍
