### ISSUE TITLE
Use configuration language

### ISSUE THREAD

**Issue by ainoya** [walter-cd/walter#18]
Consider about how to describe pipeline in configuration file more readable, efficiently.
ref. [https://github.com/hashicorp/hcl](https://github.com/hashicorp/hcl)

**Comment by jacec** [comment]
Hi @ainoya my apologies, I only just noticed this issue, I should have referenced this in my pull request, I'll add it now. See #127 which is a duplicate.

**Comment by mizzy** [comment]
I close this for cleaning issues.
