### ISSUE TITLE
Jenkins Integration: Jenkins Job Builder

### ISSUE THREAD

**Issue by maxlinc** [walter-cd/walter#59]
Walter looks like a cool project.

I saw this in the future plans at http://ainoya.io/walter:

> **Integration with Jenkins**: Feedback mechanism to tell the progress of executing Walter build pipeline to Jenkins (or other CI service) is provided.

I think an alternate approach that could have some benefits is to use Walter as a generic way to to define pipelines (and test them locally) and then use a tool to import that configuration into Jenkins or other CI/CD servers. This is similar to, or could even delegate to, [Jenkins Job Builder](http://ci.openstack.org/jenkins-job-builder/index.html) (JJB). The advantage I see of Walter over JJB is a much nicer and more portable syntax.

I think this could have some advantages over having Jenkins call walter and receive feedback on the progress. By mapping Walter definitions to existing Jenkins (or Go, TeamCity, etc.) features you'd likely be able to take better advantage of the existing pipeline visualizations, reporting, and agent pools to spread jobs across multiple machines.

**Comment by mizzy** [comment]
I close this for cleaning issues.
