### ISSUE TITLE
Cleanup stage

### ISSUE THREAD

**Issue by github1** [walter-cd/walter#78]
Is it currently possible to define a stage that always runs at the end of a pipeline? The use case I have in mind is to clean up resources created during the pipeline execution. For example:

    pipeline:
      -  stage_name: start pipeline
         stage_type: command
         command: |
           echo 'starting process'
         run_after:
           - stage_name: a_stage_that_can_fail
             stage_type: command
             command: exit 1
      - stage_name: clean_up
        stage_type: command
        command: |
          echo 'clean_up'

**Comment by ainoya** [comment]
No, it cannot execute the final stage like cleanup process. 
(With `./walter -f` option, stage execution sequence could be continued by ignoring any errors, but it may not be help what you want to do.)

I think the cleanup feature could be really needed, so I'm going to plan some implementation about that later.

**Comment by takahi-i** [comment]
I will tackle this issue. The following is the implementation image of **cleanup** feature.

https://gist.github.com/takahi-i/f7b75bcd8c02f9ed2ae7

**Comment by takahi-i** [comment]
Fix with #97
