### ISSUE TITLE
Input/Output for stages and possibly setting pipeline scope variables

### ISSUE THREAD

**Issue by derekmwright** [walter-cd/walter#96]
Feature request for sending return data from one stage to another. Also, the possibility of setting return output to a pipeline scope variable for usage in later stages.

**Comment by takahi-i** [comment]
Thank you for the feature request @derekmwright! Walter team will discuss the configuration format and  implementation.

**Comment by jacec** [comment]
:+1: for this. In addition, parameter mappings could drive stage sequencing. i.e. encouraging a declarative approach to the order similar to a Terraform plan.

**Comment by takahi-i** [comment]
Thank you for the suggestion @jacec! I have made a configuration image for local (pipeline scope) variables and the special variables for using later stages.

https://gist.github.com/takahi-i/de166bde3dece9dab2b5

**Comment by takahi-i** [comment]
I will try the implementation.

**Comment by takahi-i** [comment]
Hi @derekmwright! Walter supported special variables (__OUT, __ERR, __RESULT) to use the output of stages in later stages.

**Comment by seshun** [comment]
It would be nice , if we could pass the data from one stage to another as JSON

eg. _DATA: {"key1":"val1", "key2":"val2"}   or _DATA: ["val1","val2"]

**Comment by mizzy** [comment]
I close this for cleaning issues.
